# I have no idea what I'm doing
name: iOS Build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: iOS
    runs-on: macos-latest
    steps:
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 7

      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: actions/cache@v4
        with:
          path: |
            macos/Dependencies/build-macosx-x86_64
            macos/Dependencies/build-macosx-arm64
            macos/Dependencies/build-macosx-universal
            macos/Dependencies/downloads
          key: mac-${{ hashFiles('macos/Dependencies/*.make', 'macos/Dependencies/*.sh') }}

      - name: Install Homebrew tools
        run: |
          cd macos/Dependencies
          brew bundle

      - name: Build all dependencies
        run: |
          cd ios/Dependencies
          bash ./build.sh

      - name: Generate xxd Headers
        run: |
          # The macOS xcodebuild does not run the meson/cmake xxd targets, so we do it manually.
          # We must run this from a sibling directory so xxd creates variables starting with exactly 3 underscores (e.g. `___assets_liberation_ttf`)
          cd macos
          for f in ../shader/*.frag ../shader/*.vert ../shader/common.h; do xxd -i "$f" > "$(basename $f).xxd"; done
          xxd -i ../assets/icon.png > icon.png.xxd
          xxd -i ../assets/gamecontrollerdb.txt > gamecontrollerdb.txt.xxd
          xxd -i ../assets/liberation.ttf > liberation.ttf.xxd
          if [ -f ../assets/wqymicrohei.ttf ]; then xxd -i ../assets/wqymicrohei.ttf > wqymicrohei.ttf.xxd; fi

          # Copy to src dirs where #include looks for them based on original meson.build structure
          cp *.frag.xxd ../src/display/gl/
          cp *.vert.xxd ../src/display/gl/
          cp common.h.xxd ../src/display/gl/
          cp icon.png.xxd ../src/
          cp gamecontrollerdb.txt.xxd ../src/
          cp liberation.ttf.xxd ../src/display/
          if [ -f wqymicrohei.ttf.xxd ]; then cp wqymicrohei.ttf.xxd ../src/display/; fi

      - name: Build app
        run: |
          mkdir build && cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=../deps/ios_toolchain.cmake -G Xcode ../ios
          cmake --build . --config Release

      - name: Package IPA
        run: |
          cd build
          APP_DIR=$(find . -name "mkxpz.app" -type d | head -n 1)
          cp ../assets/LICENSE.mkxp-z-with-https.txt "$APP_DIR/"
          mkdir Payload
          cp -R "$APP_DIR" Payload/mkxp-z.app
          zip -r mkxp-z.ipa Payload

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: mkxp-z.ios.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
          path: build/mkxp-z.ipa
